name: Continus Integration

on:
  push:
    branches: ['main']

jobs:
  continus-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22
      - name: run install, build and test
        run: |
          npm i
          npm run test
          npm build
